<?php
// Do not edit this file but create an override
echo json_encode(array('chat' => $chat,'msg' => erLhcoreClassModelmsg::getList(array('limit' => 5000, 'filter' => array('chat_id' => $chat->id)))));
?>