<?php

echo json_encode(array(
    "voice_call" => [
        "join_call" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Join call'),
        "cancel_join" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Cancel'),
        "stop_share_screen" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Stop sharing your screen'),
        "share_your_screen" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Share your screen'),
        "share_video" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Enable video'),
        "stop_sharing_video" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Disable video'),
        "unmute_mic" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Un-mute mic'),
        "mute_mic" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Mute mic'),
        "end_call_op" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Call for the visitor also will end.'),
        "end_call_button" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','End the call'),
        "leave_a_call" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Leave a call. Visitor will remain on the call'),
        "leave_room" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Leave the call'),
        "leave_call_op" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Leave the call'),
        "join_with_audio" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Audio call'),
        "join_with_audio_video" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Audio & video call'),
        "let_visitor_in" => erTranslationClassLhTranslation::getInstance()->getTranslation('chat/voice_video','Let visitor in'),
        "wait_let_in" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Please wait untill operator let's you in"),
        "me_audio" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Me"),
        "wait_join_long" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Please wait untill operator let's you join the call"),
        "visitor_waiting_in" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Visitor is waiting for someone to let him in!"),
        "pending_visitor_join" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Pending visitor to join the call!"),
        "visitor_joined" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Visitor has joined the call!"),
        "audio_call" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Operator"),
        "join_to_start" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Start conversation"),
        "reconnecting" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Connection lost. Reconnecting..."),
        "network_quality" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Network quality"),
        "call_duration" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Call duration"),
        "device_error" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Could not access microphone or camera. Please check browser permissions."),
        "connect_error" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Could not connect to the call server."),
        "screen_share_error" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Screen could not be shared!"),
        "microphone" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Microphone"),
        "camera" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Camera"),
        "settings" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Devices"),
        "no_answer" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Nobody answered the call. Please try again later or continue in the chat."),
        "no_active_call" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","There is no call in progress"),
        "call_in_progress" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Call is in progress"),
        "listen" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Listen to the call"),
        "listening" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Listening. Participants are not notified."),
        "stop_listening" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Stop listening"),
        "recording_active" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","This call is being recorded"),
        "start_recording" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Start recording"),
        "stop_recording" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Stop recording"),
        "transfer" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Transfer the call"),
        "transfer_to" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Transfer the call to"),
        "no_operators" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","There are no online operators the call can be transferred to"),
        "transfer_pending" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Call continues until the operator joins. Transferring to"),
        "call_transferred" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Call was taken over by another operator."),
        "join_conversation" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","Join the conversation"),
        "speaking" => erTranslationClassLhTranslation::getInstance()->getTranslation("chat/voice_video","You are in the conversation. Participants can hear you."),
    ]
));

?>