<?php
return [
    'settings' => [
        'site' => [
            'title' => 'Live helper Chat',
            'site_admin_email' => '',
            'locale' => 'en_EN',
            'theme' => 'defaulttheme',
            'installed' => false,
            'secrethash' => '',
            'debug_output' => false,
            'debug_view' => false,
            'static_version' => 0,
            'log_slow_request' => false,
            'templatecache' => false,
            'templatecompile' => false,
            'modulecompile' => false,
            'force_virtual_host' => false,
            'proxy_mode' => false,
            'disable_mobile' => false,
            'disable_rest_api_by_user' => false,
            'one_login_per_account' => false,
            'php_session_cookie_name' => '',
            'time_zone' => 'UTC',
            'date_format' => 'Y-m-d',
            'date_hour_format' => 'H:i:s',
            'date_date_hour_format' => 'Y-m-d H:i:s',
            'default_site_access' => 'eng',
            'default_site_access_list' => ['eng'],
            'default_admin_site_access' => ['site_admin'],
            'maps_api_key' => false,
            'default_group' => '',
            'default_user' => '',
            'site_address' => '',
            'allow_iframe' => false,
            'allow_iframe_domain' => '',
            'trusted_host_patterns' => [],
            'extensions' => [
                // 0 => 'customstatus',
            ],
            'available_site_access' => [
                0 => 'eng',
                1 => 'lit',
                2 => 'hrv',
                3 => 'esp',
                4 => 'por',
                5 => 'nld',
                6 => 'ara',
                7 => 'ger',
                8 => 'pol',
                9 => 'rus',
                10 => 'ita',
                11 => 'fre',
                12 => 'chn',
                13 => 'cse',
                14 => 'nor',
                15 => 'tur',
                16 => 'vnm',
                17 => 'idn',
                18 => 'sve',
                19 => 'per',
                20 => 'ell',
                21 => 'dnk',
                22 => 'rou',
                23 => 'bgr',
                24 => 'tha',
                25 => 'geo',
                26 => 'fin',
                27 => 'alb',
                28 => 'heb',
                29 => 'cat',
                30 => 'hun',
                31 => 'svk',
                32 => 'jpn',
                33 => 'site_admin',
            ],
        ],
        'default_url' => [
            'module' => 'chat',
            'view' => 'start',
        ],
        'webhooks' => [
            'enabled' => false,
            'worker' => 'http',
            'single_event' => false,
        ],
        'chat' => [
            'online_timeout' => 300,
            'back_office_sinterval' => 10,
            'chat_message_sinterval' => 3.5,
            'check_for_operator_msg' => 10,
            'new_chat_sound_enabled' => true,
            'new_message_sound_admin_enabled' => true,
            'new_message_sound_user_enabled' => true,
        ],
        'memecache' => [
            'servers' => [
                0 => [
                    'host' => '127.0.0.1',
                    'port' => '11211',
                    'weight' => 1,
                ],
            ],
        ],
        'redis' => [
            'server' => [
                'host' => 'localhost',
                'port' => 6379,
                'auth' => null,
                'database' => 0,
            ],
        ],
        'db' => [
            'host' => getenv('LHC_DB_HOST') ?: '',
            'user' => getenv('LHC_DB_USERNAME') ?: '',
            'password' => getenv('LHC_DB_PASSWORD') ?: '',
            'database' => getenv('LHC_DB_DATABASE') ?: '',
            'port' => getenv('LHC_DB_PORT') ?: 3306,
            'use_slaves' => false,
            'tz' => '',// E.g '+02:00',
            'db_slaves' => [
                0 => [
                    'host' => '',
                    'user' => '',
                    'port' => 3306,
                    'password' => '',
                    'database' => '',
                ],
            ],
        ],
        'site_access_options' => [
            'eng' => [
                'locale' => 'en_EN',
                'content_language' => 'en',
                'dir_language' => 'ltr',
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
            ],
            'lit' => [
                'locale' => 'lt_LT',
                'content_language' => 'lt',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'svk' => [
                'locale' => 'sk_SK',
                'content_language' => 'sk',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'hrv' => [
                'locale' => 'hr_HR',
                'content_language' => 'hr',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'esp' => [
                'locale' => 'es_MX',
                'content_language' => 'es',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'dnk' => [
                'locale' => 'da_DA',
                'content_language' => 'da',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'por' => [
                'locale' => 'pt_BR',
                'content_language' => 'pt',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'nld' => [
                'locale' => 'nl_NL',
                'content_language' => 'nl',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'ara' => [
                'locale' => 'ar_EG',
                'content_language' => 'ar',
                'dir_language' => 'rtl',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'ger' => [
                'locale' => 'de_DE',
                'content_language' => 'de',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'pol' => [
                'locale' => 'pl_PL',
                'content_language' => 'pl',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'rus' => [
                'locale' => 'ru_RU',
                'content_language' => 'ru',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'ita' => [
                'locale' => 'it_IT',
                'content_language' => 'it',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'tur' => [
                'locale' => 'tr_TR',
                'content_language' => 'tr',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'fre' => [
                'locale' => 'fr_FR',
                'content_language' => 'fr',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'chn' => [
                'locale' => 'zh_ZH',
                'content_language' => 'zh',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'cse' => [
                'locale' => 'cs_CS',
                'content_language' => 'cs',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'nor' => [
                'locale' => 'no_NO',
                'content_language' => 'no',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'vnm' => [
                'locale' => 'vi_VN',
                'content_language' => 'vi',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'tha' => [
                'locale' => 'th_TH',
                'content_language' => 'th',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'idn' => [
                'locale' => 'id_ID',
                'content_language' => 'in',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'sve' => [
                'locale' => 'sv_SV',
                'content_language' => 'sv',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'per' => [
                'locale' => 'fa_FA',
                'content_language' => 'fa',
                'dir_language' => 'rtl',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'ell' => [
                'locale' => 'el_EL',
                'content_language' => 'el',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'rou' => [
                'locale' => 'ro_RO',
                'content_language' => 'ro',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'bgr' => [
                'locale' => 'bg_BG',
                'content_language' => 'bg',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'cat' => [
                'locale' => 'ca_ES',
                'content_language' => 'es',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'geo' => [
                'locale' => 'ka_KA',
                'content_language' => 'ka',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'fin' => [
                'locale' => 'fi_FI',
                'content_language' => 'fi',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'alb' => [
                'locale' => 'sq_AL',
                'content_language' => 'sq',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'heb' => [
                'locale' => 'he_HE',
                'content_language' => 'he',
                'dir_language' => 'rtl',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'hun' => [
                'locale' => 'hu_HU',
                'content_language' => 'hu',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'jpn' => [
                'locale' => 'ja_JP',
                'content_language' => 'ha',
                'dir_language' => 'ltr',
                'title' => '',
                'description' => '',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'default_url' => [
                    'module' => 'chat',
                    'view' => 'start',
                ],
            ],
            'site_admin' => [
                'locale' => 'en_EN',
                'content_language' => 'en',
                'dir_language' => 'ltr',
                'theme' => [
                    0 => 'customtheme',
                    1 => 'defaulttheme',
                ],
                'login_pagelayout' => 'login',
                'default_url' => [
                    'module' => 'front',
                    'view' => 'default',
                ],
            ],
        ],
        'cacheEngine' => [
            'cache_global_key' => 'global_cache_key',
            'className' => false,
        ],
    ],
    'comments' => NULL,
];
