<p><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Describes how long each agent was actively involved in the chat.');?></p>

<ul>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'An agent becomes active owner when a supported operator event/message appears (accept, transfer, owner/department change, assign, or operator message).');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'For each next message gap, time is added only if gap is greater than 0 and smaller than timeout. Visitor messages can increase current owner\'s time while ownership does not change.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation("genericbot/helpattributes", "When owner changes, previous owner's accumulated time is frozen. New owner continues from their own previously stored value (or 0 if first time).");?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Consecutive visitor messages do not change owner by themselves. While owner stays the same, each eligible visitor-side gap can keep increasing that owner\'s duration.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'For response metrics tied to participants (FRT/AART/MART), consecutive visitor messages also do not reset pending visitor start marker. Start remains first pending point until valid operator reply.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Accept/transfer/owner-change meta events can switch owner context, but they do not count as visitor replies. They only affect which human owner receives later eligible gaps.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Bot/auto-responder side is not tracked as a human participant owner, so it does not create a separate human agent duration entry.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Scenario: visitor writes after first acceptance. That visitor-to-next-message gap is added to accepted agent only if it is below timeout.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'Scenario: chat is transferred and accepted by another operator. After acceptance, visitor gaps are added to new owner; previous owner remains frozen.');?></li>
    <li><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'If the gap between two messages is larger than the timeout below, that gap is skipped — so a long silence does not unfairly inflate an agent\'s time.');?></li>
    <li><?php echo \erLhcoreClassModelChatConfig::fetch('cduration_timeout_user')->current_value ?> <?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'minutes — max gap allowed after a visitor message. If the agent replied later than this, that waiting time is ignored.');?></li>
    <li><?php echo \erLhcoreClassModelChatConfig::fetch('cduration_timeout_operator')->current_value ?> <?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('genericbot/helpattributes', 'minutes — max gap allowed after an agent message. If the visitor replied later than this, that waiting time is ignored.');?></li>
</ul>