export const FETCH_NODE_GROUPS = "FETCH_NODE_GROUPS";
export const FETCH_NODE_GROUPS_FULFILLED = "FETCH_NODE_GROUPS_FULFILLED";
export const FETCH_NODE_GROUPS_REJECTED = "FETCH_NODE_GROUPS_REJECTED";
export const ADD_GROUP_FULFILLED = "ADD_GROUP_FULFILLED";
export const UPDATE_GROUP_FULFILLED = "UPDATE_GROUP_FULFILLED";

// Trigger actions
export const FETCH_NODE_GROUP_TRIGGERS = "FETCH_NODE_GROUP_TRIGGERS";
export const FETCH_NODE_GROUP_TRIGGERS_FULFILLED = "FETCH_NODE_GROUP_TRIGGERS_FULFILLED";
export const FETCH_NODE_GROUP_TRIGGERS_REJECTED = "FETCH_NODE_GROUP_TRIGGERS_REJECTED";

// Trigger response actions
export const FETCH_TRIGGER_RESPONSE = "FETCH_TRIGGER_RESPONSE";
export const FETCH_TRIGGER_RESPONSE_FULFILLED = "FETCH_TRIGGER_RESPONSE_FULFILLED";
export const FETCH_TRIGGER_RESPONSE_REJECTED = "FETCH_TRIGGER_RESPONSE_REJECTED";
export const UPDATE_TRIGGER_NAME = "UPDATE_TRIGGER_NAME";
export const UPDATE_TRIGGER_TYPE = "UPDATE_TRIGGER_TYPE";

// Add new trigger callback
export const ADD_TRIGGER_FULFILLED = "ADD_TRIGGER_FULFILLED";
export const ADD_TRIGGER_RESPONSE = "ADD_TRIGGER_RESPONSE";
export const HANDLE_CONTENT_CHANGE = "HANDLE_CONTENT_CHANGE";
export const SAVE_TRIGGER = "SAVE_TRIGGER";
export const REMOVE_TRIGGER = "REMOVE_TRIGGER";