export const FETCH_NODE_GROUPS = "FETCH_NODE_GROUPS";
export const FETCH_NODE_GROUPS_FULFILLED = "FETCH_NODE_GROUPS_FULFILLED";
export const FETCH_NODE_GROUPS_REJECTED = "FETCH_NODE_GROUPS_REJECTED";
export const ADD_GROUP_FULFILLED = "ADD_GROUP_FULFILLED";
export const UPDATE_GROUP_FULFILLED = "UPDATE_GROUP_FULFILLED";