<?php

echo json_encode(array(
    "mail" => [
        "follow_up" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Follow up of'),
        "op_watching" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Operator who has opened this ticket'),
        "wait_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Wait time'),
        "copied" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Copied'),
        "copy_link" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Copy link'),
        "sender" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Sender'),
        "status" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Status'),
        "close" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Close'),
        "delete" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Delete ticket'),
        "interactions_history" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Interactions history'),
        "print" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Print'),
        "transfer_chat" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Transfer ticket'),
        "closed_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Closed at'),
        "responded_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Responded at'),
        "last_responded_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Last time responded at'),
        "interaction_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Interaction time'),
        "last_interaction_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Last interaction time'),
        "priority" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Priority'),
        "chat_owner" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Ticket owner'),
        "received" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Last mail received at'),
        "accepted_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Accepted at'),
        "last_accepted_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Last time accepted at'),
        "department" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Department'),
        "information" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Information'),
        "remarks" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Remarks'),
        "send_fetching" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Your new message being fetched. If you just send a message you can close this conversation in any case.'),
        "accepted_by" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Accepted by'),
        "accept_wait_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Accept wait time'),
        "response_wait_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Response wait time'),
        "exc_pending_time" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Exc. pending time'),
        "conv_duration" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Conversation duration'),
        "phone" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Phone'),
        "merge_chat" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Merge'),
        "yes" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Yes'),
        "no" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','No'),
        "sure_close" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Are you sure?'),
        "subject" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Subject'),
        "previous_messages" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Previous messages'),
        "block" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Block sender'),
        "is_blocked" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Sender is blocked!'),
        "rsp_type" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Response type')
    ],
    "status" => [
        "pending" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','New'),
        "active" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Active'),
        "closed" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Closed'),
        "opened_at" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Opened at'),
        "are_you_sure" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Are you sure?'),
        "unresponded_messages" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','There is still un-responded messages, are you sure you want to close this conversation?')
    ],
    "msg" => [
        "reply" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Reply'),
        "forward" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Forward'),
        "download" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Download (eml)'),
        "no_reply" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','No reply required'),
        "info" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Message information'),
        "from" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','from'),
        "to" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','to'),
        "reply_to" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','reply-to'),
        "mailed_by" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','mailed-by'),
        "nrr" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','No reply required'),
        "orm" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','This is our response message'),
        "rbe" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Responded by e-mail'),
        "unr" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Un-responded'),
        "ago" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','ago'),
        "ar_label" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Add/Remove label'),
        "send" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Send'),
        "sending" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Sending...'),
        "click_to_remove" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Click to remove'),
        "not_an_owner" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','You are not the owner of this conversation. This means someone else was working with this ticket. Make sure you want to send a reply to this e-mail.'),
        "plain_html" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','View as Plain/HTML'),
        "send_and_close" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Send as Closed'),
        "send_as_pending" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Send as New'),
        "send_as_active" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Send as Active'),
        "opened_at_message" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Message was seen by customer first time at'),
        "merged_message" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','This is a merged message'),
        "unmerge" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Un-merge'),
        "self_reply" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','You are replying to your mailbox. Make sure that it is your intent!'),
        "external_email" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','External e-mail!'),
        "internal_email" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','This is our mailbox e-mail!'),
        "pnd_rsp" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Pending response'),
        "rsp" => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Responded')
    ],
    "r" => [
        'recipients' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Recipients'),
        'to' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','To'),
        'email' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','E-mail'),
        'name' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Recipient name'),
    ],
    "system" => [
        'error' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Seems there is some connectivity problem with a server!'),
    ],
    "file" => [
        'incorrect_type' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Incorrect file type'),
        'to_big_file' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','File to big'),
        'uploading' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Uploading'),
        'choose_uploaded' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Choose file from uploaded files'),
        'drop_here' => erTranslationClassLhTranslation::getInstance()->getTranslation('module/mailconv','Drop your files here or choose a new file')
    ]
));

?>